### PR TITLE
Wms feature info

### LINKED ISSUE #11: Handle WMS layers more gracefully
Possibly related to #8, but for WMS.

Todays implementation handles WMS layers (and all other non-vector layers) by assuming there is a WFS endpoint at the same url as the image layer. This may very often be true when it comes to WMS:es hosted by the own organization as Geoserver for instance default have both WMS and WFS enabled. But for many other setups this assumption will fail.

Suggested ways around this:
1. Add a configuration if the WFS endpoint should be tried.
2. Implement something like featureInfoLayer configuration to make it possible to point out any arbitrary layer to get features from.
3. Implement something that actually fetches the features from WMS.

Solution 2 would probably require some additions to the core, either a touch up of the getFeatures utility function to support different SRS and possibly some other changes to make it more versatile or move the getFeature functionality to a VectorSource class. At least getFeature and the VectorSource should be consolidated in some way to avoid the loader function to be almost exactly the same as getFeatures, but that's an issue for the core. Maybe its possible to extend the featureInfoLayer handling in core to allow for more layer types and expose that functionality as an api function using an extent as input instead of just a point.

Solution 3 kind of defeats some of the reasons to use WMS, but could be possible using vendor specific parameters to getFeatureInfo. Geoserver has a search radius parameter which could be used to create a query that fetches the outer circle of the extent and Qgis server has a vendor specific parameter that can take an intersecting geometry. For other server types (AGS WMS etc) this approach will not work unless there is a vendor specific parameter as the WMS standard only specifies a X,Y pair to query.

### PR DESCRIPTION
**Pull request by steff-o**
Resolves #11 by implementing two different strategies depending on the situation. Both strategies are only fully supported on Geoserver and supports filters (_CQL_FILTER_) on the wms layer. Technically the same approach would be easy to implement for Qgis and most likely AGS as well. But as Origo currently lacks an api-function for determining the kind of server for a layer, I chose not to implement yet another variant of that.

__1 By configuration__
Alternative layers can be configured for each layer by adding the property `alternativeLayers`to the MultiSelect configuration. Each layer can have many alternative layers to support composite WMS layers.
```javascript
const alternativeLayers = [
            {
              name: 'kombolager',
              queryInfoLayers: ['punktlager', 'multipolygonlager'],
              disableFilterHandling: false
            }
        ];
```
`name`:  is the name of the layer in origo configuration for which the configuration applies to. The layer could be any kind of layer, but the filter feature only works for Geoserver WMS.

`queryInfoLayers`: List with names of layers from which features will be selected instead of the original layer. Only layer types that are implemented in Origo.getFeature() (WFS and AGS feature) is possible to use, but the filter feature only works for Geoserver WFS. Due to a limitation in Origo.getFeature() only layers that have the same default (on server) coordinate system as the map works. Alternative layers must be configured in origo configurantion and should be hidden and not added to the legend and not used for anything else to make sense and not get messed up by the filter handling.

`disableFilterHandling`: If the configured layer is a WMS layer and has a _CQL_FILTER_ property set the default behavior is to set that filter on the alternative layers as well, which only works when the origonal layer is a Geoserver WMS layer and the alternative layer is a Geoserver WFS layer. As the current implementation of WFS layers in origo does not really support changing the filter and if using a different server than Geoserver this flag can be set to true to avoid trouble if not using filters. Defaults to _false_.

__2 By changing default WMS behavior__
By setting `WMSHandling: { source: "WMS" }` on the MultiSelect configuration the default behavior of WMS- layers is changed to get the selected features from the WMS server itself instead of trying to get them from an implicit WFS endpoint. The setting applies to all WMS layers in the map. If a layer has an `alternativeLayers`-configuration it takes precedence over the WMSHandling.

The implementation works by creating a fetureInfo-request to the WMS server. If the layer has a filter it will be honored, which works for both Geoserver and QGis and probably just about any server that supports filters, but as a Geoserver vendor specific parameter is used to create an extent instead of just a feataureinfo point, it only works for Geoserver.

### CODE REVIEW

**Comment by steff-o** [comment]
@asemoller Could you check if this breaks anything for you? Everything should be opt-in so you don't have to test if it actually works.

We would prefer to merge these changes instead of keeping it in our own fork but there seems to be lack of interest for this codebase from most other parties at the moment. I think that others will come along soon when they start to use origo more in internal applications and therefore it would be nice to keep a common codebase from the start.

**Comment by asemoller** [comment]
@steff-o I'll have a look!


> We would prefer to merge these changes instead of keeping it in our own fork but there seems to be lack of interest for this codebase from most other parties at the moment. I think that others will come along soon when they start to use origo more in internal applications and therefore it would be nice to keep a common codebase from the start.

I totally agree.

**Comment by asemoller** [comment]
Nothing seemed to break when I tested.

**Comment by asemoller** [comment]
Maybe someone else should test the functionality regarding the settings. Most of the WMS's we have are external and this solution doesn't seem to solve that problem (unless it's from geoserver?).

**Comment by steff-o** [comment]
Yes, it only works for Geoserver, but as all new functionality is opt-in it should default to the old behavior, which didn't work for most public WMS:es either... The problem is that there is no way to write it to work with all server types as the functionality relies on vendor specific parameters. It would be possible to write for at least AGS and Qgis if featureInfo is not turned off, but that would require knowing the server type beforehand. Instead of doubling that functionality, I was hoping to get that as an API-function in Origo before jumping in to implement all different kinds of vendor specific stuff. And to be honest, at the moment we are only are interested in our own Geoserver and I prefer merging this quickly and take some bugfixes and finetuning later as we have more PR:s in the pipe and would like to avoid keeping our own fork and the merging problems that will arise.

@jokd Any thoughts on if we can merge it as is?

**Pull request merged**
